openapi: 3.0.3

info:
  title: Medaware Catalyst
  description: The API Specification for Medaware
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development environment

paths:
  /:
    get:
      operationId: catalystStatus
      summary: A status endpoint
      tags:
        - Status
      responses:
        200:
          description: Medaware Catalyst is up and running
          content:
            text/plain:
              schema:
                type: string

  /register:
    post:
      operationId: catalystRegister
      summary: Register a new Medaware user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registrationRequest"
      responses:
        200:
          description: User successfully registered

  /login:
    post:
      operationId: catalystLogin
      summary: Provide authentication facilities for existing users
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginRequest"
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tokenResponse"

  /logout:
    post:
      operationId: catalystLogout
      summary: Log out a logged-in user
      tags:
        - Authentication
      responses:
        200:
          description: OK

  /article:
    post:
      operationId: catalystCreateArticle
      summary: Create a new article
      tags:
        - Article
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - title
                - lead
                - html
              properties:
                title:
                  type: string
                lead:
                  type: string
                html:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uuidResponse"

  /public/articles:
    get:
      operationId: catalystGetAllArticles
      summary: Retrieve all articles
      tags:
        - Public
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/articleSearchResponse"

  /public/article:
    get:
      operationId: catalystGetArticle
      summary: Retrieve a full article by ID
      tags:
        - Public
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - title
                  - lead
                  - html
                properties:
                  title:
                    type: string
                  lead:
                    type: string
                  html:
                    type: string
        404:
          description: Article not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/catalystError"

  /public/search:
    get:
      operationId: catalystQueryArticle
      summary: Search existing articles by querying lucene
      tags:
        - Public
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/articleSearchResponse"

components:
  schemas:
    catalystError:
      type: object
      required:
        - brief
        - message
        - status
      properties:
        brief:
          type: string
        message:
          type: string
        status:
          type: integer

    registrationRequest:
      type: object
      required:
        - userName
        - firstName
        - lastName
        - password
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string

    loginRequest:
      type: object
      required:
        - userName
        - password
      properties:
        userName:
          type: string
        password:
          type: string

    tokenResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string

    uuidResponse:
      type: object
      required:
        - uuid
      properties:
        uuid:
          type: string
          format: uuid

    briefArticleResponse:
      type: object
      required:
        - title
        - lead
        - id
      properties:
        title:
          type: string
        lead:
          type: string
        id:
          type: string
          format: uuid

    articleSearchResponse:
      type: array
      items:
        $ref: "#/components/schemas/briefArticleResponse"