openapi: 3.0.3

info:
  title: Medaware Catalyst
  description: The API Specification for Medaware
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development environment

paths:
  /:
    get:
      operationId: catalystStatus
      summary: Catalyst status endpoint
      tags:
        - Status
      responses:
        200:
          description: Medaware Catalyst is up and running
          content:
            text/plain:
              schema:
                type: string

  /secured:
    get:
      operationId: securedRoute
      summary: A secured status route
      tags:
        - Security
      responses:
        200:
          description: Medaware Catalyst is up and running
          content:
            text/plain:
              schema:
                type: string

  /antg/compile:
    post:
      operationId: compileAnterogradia
      summary: Compile Anterogradia sources
      tags:
        - Anterogradia
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: Compilation successful
          content:
            text/html:
              schema:
                type: string

  /tan/login:
    post:
      operationId: tangentialLogin
      summary: Log-in to the Tangential system
      tags:
        - Tangential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tangentialLoginRequest"
      responses:
        200:
          description: Log-in successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tangentialSessionResponse"

  /tan/logout:
    post:
      operationId: tangentialLogout
      summary: Invalidate the current user's session
      tags:
        - Tangential
      responses:
        200:
          description: Logged out

  /tan/articles/own:
    get:
      operationId: listOwnArticles
      summary: Get a list of articles written by the currently logged-in user
      tags:
        - Tangential
      responses:
        200:
          description: Articles returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/articleListing"


components:
  schemas:
    tangentialLoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    tangentialSessionResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string

    catalystError:
      type: object
      required:
        - summary
        - message
      properties:
        summary:
          type: string
        message:
          type: string

    articleListing:
      type: array
      items:
        $ref: "#/components/schemas/articleResponse"

    articleResponse:
      type: object
      required:
        - author
        - title
        - date
      properties:
        author:
          type: string
        title:
          type: string
        date:
          type: string
          format: date
        id:
          type: string
          format: uuid